name: Check for words 'hola' and 'adios'

on:
  pull_request:
    paths:
      - 'gef.py'

jobs:
  check-words:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # We need the full history to be able to diff

      - name: Check for 'hola' and 'adios' in gef.py
        run: |
          WORDS=("hola" "adios")
          for word in "${WORDS[@]}"; do
            if git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- "gef.py" | grep "^+" | grep -q "$word"; then
              echo "::warning '$word' found in gef.py. Consider removing it."
            fi
          done
